CREATE TABLE "GCG_3744_IV_BTB_XFER"(
 "BIRUNID" BIGINT,
 "MATERIAL" CHAR(20),
 "BIN" CHAR(6),
 "QTY_ON_LABEL" DOUBLE,
 "LBL_CREATE_DATE" DATE,
 "LOT" CHAR(15),
 "SIZE" CHAR(30),
 "INV_UM" CHAR(2),
 "USER_ID" CHAR(8));